
version: '3'
services:
  mysql:
    image: mysql:5.6
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql-mode=''
    restart: always
    ports:
      - '9001:3306'
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: dev_db
      TZ: Asia/Seoul
    platform: linux/x86_64


  # tt-nginx:
  #   image: nginx:1.17.3
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - ./nginx/site-enabled/:/etc/nginx/site-enabled/
  #   ports:
  #     - 80:80
  #     - 443:443

  # tt-api:
  #   image: tt-api:latest
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   restart: 'always'
  #   volumes:
  #     - ./:/travel-together/
  #   ports:
  #     - 3000:3000
